// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5moPZPpe5LTTu5oub-gMPEgoVmb-ItDM',
    appId: '1:666859019528:web:2469a5468e377aaf1da0bd',
    messagingSenderId: '666859019528',
    projectId: 'majika-ai-recommendation',
    authDomain: 'majika-ai-recommendation.firebaseapp.com',
    storageBucket: 'majika-ai-recommendation.firebasestorage.app',
    measurementId: 'G-D9TXSQF1G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFfScWLBDhrJ7lOLc5Wt6q2ocOKZajJo',
    appId: '1:666859019528:android:0e792942d89b8bd31da0bd',
    messagingSenderId: '666859019528',
    projectId: 'majika-ai-recommendation',
    storageBucket: 'majika-ai-recommendation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39eb5rA6hwZ5cODIrlbdhqDMbWdGw6pM',
    appId: '1:666859019528:ios:31cabe7d74d1a8461da0bd',
    messagingSenderId: '666859019528',
    projectId: 'majika-ai-recommendation',
    storageBucket: 'majika-ai-recommendation.firebasestorage.app',
    iosBundleId: 'de.khonager.majika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39eb5rA6hwZ5cODIrlbdhqDMbWdGw6pM',
    appId: '1:666859019528:ios:31cabe7d74d1a8461da0bd',
    messagingSenderId: '666859019528',
    projectId: 'majika-ai-recommendation',
    storageBucket: 'majika-ai-recommendation.firebasestorage.app',
    iosBundleId: 'de.khonager.majika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5moPZPpe5LTTu5oub-gMPEgoVmb-ItDM',
    appId: '1:666859019528:web:387bbd7447ec0b6e1da0bd',
    messagingSenderId: '666859019528',
    projectId: 'majika-ai-recommendation',
    authDomain: 'majika-ai-recommendation.firebaseapp.com',
    storageBucket: 'majika-ai-recommendation.firebasestorage.app',
    measurementId: 'G-4NM4P8EVP9',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC5moPZPpe5LTTu5oub-gMPEgoVmb-ItDM',
    appId: '1:666859019528:web:2469a5468e377aaf1da0bd',
    messagingSenderId: '666859019528',
    projectId: 'majika-ai-recommendation',
    authDomain: 'majika-ai-recommendation.firebaseapp.com',
    storageBucket: 'majika-ai-recommendation.firebasestorage.app',
    measurementId: 'G-D9TXSQF1G8',
  );
}
